version: "3"
services: 
    app:
        build: .
        ports: 
            - 8080:8080
        restart: always
        working_dir: /home/app
        tty: true
        networks:
            - app-network
        depends_on:
            - mongo
    mongo:
        image: mongo
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        networks:
            - app-network
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
        networks:
            - app-network
        networks:
            app-network:
                external: true
                