version: "3.0"
services: 
    app:
        build: .
        ports: 
            - 8080:8080
        restart: always
        working_dir: /home/app
        tty: true
        depends_on:
            - mongo, mongo-express
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        links:
            - 'mongo:mongo'
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
                